### ISSUE TITLE
bug: calling get_waku_v2_admin_v1_peers crashes nwaku

### ISSUE THREAD

**Issue by dao** [waku-org/nwaku#1505]
### Problem
Executing JSON-RPC method `get_waku_v2_admin_v1_peers` is crashing one nwaku node, but not others.

Executing `get_waku_v2_debug_v1_info` does not crash the node

### Impact
Severe - 

### To reproduce
The nwaku instance which crashes on peers query is one which is used by WSS clients. The nodes which do not crash are not. I cannot think of any other significant differences in configuration.

Configuration:

```
log-level='DEBUG'
relay=true
store=false
filter=false
lightpush=false
rln-relay=false
rpc=true
rpc-admin=false
rpc-private=true
rpc-address='0.0.0.0'
rpc-port=8546
relay-peer-exchange=false
keep-alive=true
ports-shift=0
dns-discovery=false
discv5-discovery=false
```
(+ usual secure websocket flags)

### Expected behavior
Should list peers and connection status

### Screenshots/logs
[get_peers.txt](https://github.com/waku-org/nwaku/files/10492466/get_peers.txt)

### nwaku version/commit hash
0.14.0

**Comment by alrevuelta** [comment]
Thanks for reporting it! Looks like when a peer doesnt contain any address it crashes [here](https://github.com/waku-org/nwaku/blob/master/waku/v2/node/jsonrpc/admin_api.nim#L68) since ofc `[0]` is out of bound, because its empty.

Managed to reproduce the issue with a test, and will followup with a fix here: https://github.com/waku-org/nwaku/pull/1507

But beyond this specific issue which ofc its wrong, wondering why we end having a peer that doesn't contain any multiaddress.

**Comment by jm-clius** [comment]
Interesting. Thanks @alrevuelta. Note that @dao found this issue while investigating why `wss` connections to this node appears to break after about 30 mins. Perhaps these issues are related? I think the debug logs for the node while connecting to the `wss` port and at the point when this connection is lost may go some way to help us understand what's happening.
