### ISSUE TITLE
bug: light push response is empty when protobuf decode fails

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#1641]
### Problem

When js-waku client tries to use light push with a waku message that has no content topic, nwaku sends an empty response back.

Expected: an error in the light push response to point towards decoding issue.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Start nwaku with light push
2. Send a light push rpc request that contains a missing protobuf field such as content topic
3. get an empty rpc light push response

### Expected behavior

rpc light push response contains an error

### Screenshots/logs

[nwaku_Waku_Light_Push_[node_only]_Push_successfully.log](https://github.com/waku-org/nwaku/files/11137022/nwaku_Waku_Light_Push_.node_only._Push_successfully.log)

```
ERR 2023-04-03 20:00:14.214+10:00 failed to decode rpc                       topics="waku lightpush" tid=147839 file=protocol.nim:43
```

### nwaku version/commit hash
v0.16.0

**Comment by Ivansete-status** [comment]
Although this issue has the "rpc" word in many places and even within the `nwaku` code, this issue is not directly replicable throughout the "JSON RPC" service. The issue, on the other hand, is related to the `lightpush` protocol directly, i.e. the fix candidate will likely come from near the next point https://github.com/waku-org/nwaku/blob/9085b1b3ba95dd8993236f6b2f121f45ccbd406b/waku/waku_lightpush/protocol.nim#L42

@fryorcraken - How can easily send different `js-waku` requests to `nwaku`? We have the next example but I think we cannot enforce sending an empty content topic: https://examples.waku.org/light-js/

**Comment by fryorcraken** [comment]
Yes it's _RPC_ as `PushRPC` payload https://rfc.vac.dev/spec/19/

> @fryorcraken - How can easily send different js-waku requests to nwaku? We have the next example but I think we cannot enforce sending an empty content topic: [examples.waku.org/light-js](https://examples.waku.org/light-js/)

I would recommend to use nwaku as a client to reproduce/test.

Here is how we set the content topic to send messages in js-waku: https://github.com/waku-org/js-waku/blob/d049ebbc3417e5c20eccba3aa1b9fc5382e8d7fc/packages/tests/tests/light_push.node.spec.ts#L22

However an empty content topic is now explicitly forbidden: https://github.com/waku-org/js-waku/blob/d049ebbc3417e5c20eccba3aa1b9fc5382e8d7fc/packages/core/src/lib/message/version_0.ts#L79C1-L79C1

**Comment by b4s36t4** [comment]
https://github.com/waku-org/nwaku/blob/dac072f843474f56f2f5dfe2f64972158a55628a/waku/waku_lightpush/protocol.nim#L42-L45

The issue is here if we are failed to parse the proto we're just returning ideally we should return the response https://github.com/waku-org/nwaku/blob/dac072f843474f56f2f5dfe2f64972158a55628a/waku/waku_lightpush/protocol.nim#L76-L77 just like we did here. 

Extending the response and sending it back should solve the issue.

**Comment by s-tikhomirov** [comment]
Looking at the [existing two tests for Lightpush](https://github.com/waku-org/nwaku/blob/v0.20.0/tests/test_waku_lightpush.nim), I don't quite understand how they work (which may be explained by my lack of Nim knowledge, I admit, but still).

We have two tests: for a successful and for an erring case. What I don't understand is how the outcome of the test depends on what actually happens. 

In particular, for the success-case, the handler returns an OK (as it seems to me) irrespective of the actual result of the push:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L47

And then we check that the result is indeed OK:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L66

Likewise, for the fail-case test, the handler returns an error:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L91

And then we check that the result is indeed an error:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L110

For me it looks like these tests always pass by definition. What am I missing?

**Comment by s-tikhomirov** [comment]
Also, I have a meta-question here. Shall we distinguish between "no content topic" and "empty content topic"? For me it seems that the former is a decoding issue, while the latter is more high-level one, related to interpretation of data.

Should we treat an _empty_ content topic as a decoding error too? After all, the protobuf in this case is _decoded_ successfully, it just so happens that one of the fields equals some special value (an empty string), which the spec forbids.

If we treat an empty content topic similarly to a missing one, then I would introduce a new check here, so that we additionally check whether `topic == ""`:

https://github.com/waku-org/nwaku/blob/11e7394e0d767e3d7aa570c92d404c2c6e03bfce/waku/waku_core/message/codec.nim#L46-L49

Otherwise, we could check for `topic == ""` in the Lightpush protocol, inserting an additional check between these lines:

https://github.com/waku-org/nwaku/blob/11e7394e0d767e3d7aa570c92d404c2c6e03bfce/waku/waku_lightpush/protocol.nim#L56-L57

Any thoughts?

**Comment by SionoiS** [comment]
> Looking at the [existing two tests for Lightpush](https://github.com/waku-org/nwaku/blob/v0.20.0/tests/test_waku_lightpush.nim), I don't quite understand how they work (which may be explained by my lack of Nim knowledge, I admit, but still).

I've stumble upon tests like that before. They don't test "end to end", in this case the best would be to actually check if the message was send via `RELAY` by having the node subscribe to the topic then check the cache.

> Also, I have a meta-question here. Shall we distinguish between "no content topic" and "empty content topic"? For me it seems that the former is a decoding issue, while the latter is more high-level one, related to interpretation of data.

IMO a clear separation between protocol error and in this case decode error would be best.

**Comment by s-tikhomirov** [comment]
> in this case the best would be to actually check if the message was send

Ok, I'm gonna go step by step here.

In a test, how do I create a server that uses the actual handler described in the protocol, instead of a mock handler that always returns `Ok` or `Err`?

In particular, how do I bring the logic from here:

https://github.com/waku-org/nwaku/blob/11e7394e0d767e3d7aa570c92d404c2c6e03bfce/waku/waku_lightpush/protocol.nim#L38-L77

to here:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L94

?

**Comment by SionoiS** [comment]
You don't have to. The handler you pass to `new` is wrapped by the one in `initProtocolHandler`

Currently the test is very narrow, what I meant to say was that it maybe better broaden the scope.

Narrow: 
1. light push client -> light push server
2. send whatever via light push
3. if handler called :heavy_check_mark: 

Broader:
1. light push client -> light push server
4. client send specific message on topic
5. if handler called with the same topic and message :heavy_check_mark: 

Very Broad:
1. light push client node connect to server node with relay & light push
2. server node subscribe to topic.
3. client node send message on topic via light push
4. get message on server node via relay api
5. if message match :heavy_check_mark: 

Hope it helps :)

**Comment by s-tikhomirov** [comment]
> The handler you pass to `new` is wrapped by the one in `initProtocolHandler` L62

I'm not sure I understand how "wrapping" works exactly...

In the test, we initialize a server passing `handler` as an argument, where `handler` is defined just above:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L45-L50

How does this linked to `initProtocolHandler`

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L38

and L62 in particular?

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L62

**Comment by SionoiS** [comment]
> > The handler you pass to `new` is wrapped by the one in `initProtocolHandler` L62
> 
> I'm not sure I understand how "wrapping" works exactly...

When `WakuLightPush` is created handler `A` is saved in the object.
https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L36

Then `initProtocolHandler` is called and create handler `B` that calls `A` and take it's place in the object.
https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L79

Resulting in handler `B` "wrapping" handler `A`

**Comment by fryorcraken** [comment]
Related: https://github.com/waku-org/nwaku/issues/2059

**Comment by s-tikhomirov** [comment]
> Maybe this GC magic is unfamiliar to you?

That's quite likely!

This what I think I understand (please correct me if I'm wrong). In `protocol.nim` we define the `WakuLightPush` protocol. Its initialization is defined in `proc new`:

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L86-L87

Here, the `pushHandler` is the "core" handler, so to say (or handler `A`). AFAICT, it is responsible for actually pushing a message to the network. Meanwhile, inside `initProtocolHandler`, we define `proc handle` that preliminary checks that the request is correctly formatted. If all checks pass, `pushHandler` is called from within `handle`:

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L62

Finally, we assign `handle` (handler `B`) as handler:

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L79

Here, I can see how `handler` wraps `pushHandler`.

~~But how is this all linked to what happens in the test?~~ While I was writing this question, I think I understood it :D I'll outline it here anyway.

In the test, we initialize the server here:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L50

where inside `newTestWakuLightpushNode` we have:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L20

And the `handler` is defined here:

https://github.com/waku-org/nwaku/blob/57e511fc833f421d24ca54460d0c5b284e70e4fe/tests/test_waku_lightpush.nim#L45-L47

My confusion was caused by the fact that **what is called `handler` in the test, is called `pushHandler` in the protocol definition**. I failed to see that `handler` in the test plays the role of the "internal" handler, which for testing purposes simply returns `Ok` or `Err`. But that's not a problem for testing the "outer" handler functionality (checking decoding errors, etc), as it is "wrapped" around `handler` in any case.

Thank you so much @SionoiS for your time, your comments are truly helpful!

**Comment by s-tikhomirov** [comment]
A more high-level question: what is the expected behavior w.r.t. client-server interaction in case the client sends an invalid request?

As an example, consider the case when the request can't be decoded.

From what I see, on the server side, the handler will `return` and will not generate any `PushResponse`:

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/protocol.nim#L42-L45

On the client side, however, it seems that the client is expecting a push response for erring cases (or is it?):

https://github.com/waku-org/nwaku/blob/a01b63aaae486623a319076d4b7c64368d3c538f/waku/waku_lightpush/client.nim#L60-L65

How should such cases be handled generally? I mean the scenarios when a client sends a request to a server, but the request is invalid in come way, so no message is actually pushed to the Relay network. How should the server respond? Should this case be handled differently from a scenario when a server did push a correctly formatted request but it failed due to issues on the Relay side?

**Comment by SionoiS** [comment]
> My confusion was caused by the fact that **what is called `handler` in the test, is called `pushHandler` in the protocol definition**. I failed to see that `handler` in the test plays the role of the "internal" handler, which for testing purposes simply returns `Ok` or `Err`. But that's not a problem for testing the "outer" handler functionality (checking decoding errors, etc), as it is "wrapped" around `handler` in any case.
> 
> Thank you so much @SionoiS for your time, your comments are truly helpful!

Actually i just realized that I did not understand how it worked either.

Because https://github.com/waku-org/nwaku/blob/1c4533a27a9f084f4036a7b15993ef3f431636d5/waku/waku_lightpush/protocol.nim#L33
and
https://github.com/waku-org/nwaku/blob/1c4533a27a9f084f4036a7b15993ef3f431636d5/waku/waku_lightpush/protocol.nim#L79
The handlers call order is;
1. libp2p calls https://github.com/waku-org/nwaku/blob/1c4533a27a9f084f4036a7b15993ef3f431636d5/waku/waku_lightpush/protocol.nim#L39
2. https://github.com/waku-org/nwaku/blob/1c4533a27a9f084f4036a7b15993ef3f431636d5/waku/waku_lightpush/protocol.nim#L62
3. https://github.com/waku-org/nwaku/blob/1c4533a27a9f084f4036a7b15993ef3f431636d5/waku/node/waku_node.nim#L828-L839

> How should such cases be handled generally? I mean the scenarios when a client sends a request to a server, but the request is invalid in some way, therefore no message is pushed to the Relay network. How should the server respond? Should this case be handled differently from a scenario when a server did push a message, but the push failed due to issues on the Relay side?

IMO always sending a response is best. We don't do that here for some reason.... Good error messages are also important.
In this case having more standard errors (maybe added to the spec.) would improve things greatly.

**Comment by NagyZoltanPeter** [comment]
@s-tikhomirov from now on, you can use Rest API to test/debug lightpush. 
Also test_rest_lightpush.nim does end to end test and failure cases. You will find it on master.
