### ISSUE TITLE
chore(rln-relay): manage eth rpc reconnections with max retries

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1958]
### Background
context: https://github.com/waku-org/nwaku/pull/1955#discussion_r1306375530

### Details
we need to have a delay + maximum number of retries to connect to an eth rpc url

### Acceptance criteria
- [ ] better connection handling using delay + maximum number of retries

**Comment by fryorcraken** [comment]
@alrevuelta @jm-clius should this be part of https://github.com/waku-org/pm/issues/70 ?

**Comment by jm-clius** [comment]
My feeling is that https://github.com/waku-org/pm/issues/70 should only track issues in the critical path, so that we can keep prioritising issues that's absolutely necessary for network launch. Non-critical but important issues, such as this one, should probably be tracked outside TWN Gen 0 milestone?

**Comment by fryorcraken** [comment]
Yes this sounds like some post gen0 hardening :+1:

**Comment by alrevuelta** [comment]
Is this related to this? https://github.com/waku-org/nwaku/pull/2537

**Comment by rymnc** [comment]
Not exactly, this issue can be closed since it was already addressed
earlier, using the retryWrapper template.

My draft PR is to test missed commitments, which I am unable to reproduce
at this time.
