### ISSUE TITLE
chore: enable rest api interface by default on wakunode

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2137]
### Background
As rest interface is now close to feature ready this issue derived from a research discussion.
By having enable rest endpoint by default would help operators manage their nodes while still keep the opt for switch it off of set certain ip and port.

Also maybe related to two other chores:
- [chore: Rest API requests on not installed endpoints shall return meaningful message along with Http404](https://github.com/waku-org/nwaku/issues/2135)
- [chore: wakunode2: allow filter and lightpush clients without pre-specify service node](https://github.com/waku-org/nwaku/issues/2136)

**Comment by NagyZoltanPeter** [comment]
> Not sure what would be the action item here. Just set `true` as the default value for `rest` flag?

I guess mostly yes! This is more a tracking issue and there are other related ones, mentioned above.
It is useful for track release content as well.
Maybe it can be connect also to removing json-rpc as planned? Any thoughts?

**Comment by jm-clius** [comment]
With the REST API complete, I agree that it should be enabled by default.
Afaik, with the possible exception of the "Admin API", all our APIs are client-side APIs (e.g. filter _client_, store _client_, etc.). 
Since IMO all waku nodes (regardless of configuration) should be capable of acting as filter, store, lightpush, peer-exchange _clients_ (in other words, the necessary protocols should be mounted/configured) the APIs can all be enabled for any waku node.
