### ISSUE TITLE
bug: Relayed messages are not stored when running nwaku with docker compose

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2380]
### To reproduce
1. Setup a RLN RELAY node as described [here](https://docs.waku.org/guides/nwaku/run-docker-compose) (the only thing I changes is the nwaku version in docker compose yaml. I used harbor.status.im/wakuorg/nwaku:v0.24.0)
2. Publish some messages like in the guide
3. Query the messages using the store protocol like in the guide

### Actual behavior
No message found, and I see in the logs errors : `failed to insert message                   topics="waku archive" tid=1 file=archive.nim:121 err="failed prepare in runStmt: ERROR:  column \"messagehash\" of relation \"messages\" does not exist\nLINE 1: INSERT INTO messages (id, messageHash, storedAt, contentTopi...\n                                  ^\n"`

Docker logs 

[nwaku_docker_logs.txt](https://github.com/waku-org/nwaku/files/14081348/nwaku_docker_logs.txt)

**Comment by fbarbu15** [comment]
Duplicate of https://github.com/waku-org/nwaku/issues/2196

**Comment by Ivansete-status** [comment]
Hi @fbarbu15 ! While checking this issue I realised that this isn't related to #2196

In this case, the version `harbor.status.im/wakuorg/nwaku:v0.24.0` is expecting the database to have the `messageHash` column. This issue happens because we missed to properly implement a migration script that will adapt the table and add the appropriate `messageHash` column.

The simpler fix for you in this case is just completely remove your local database and start it again.

Sorry for the inconvenience and let me know if any other issue happens, and thanks for submitting this btw!

**Comment by fbarbu15** [comment]
Worked, thanks!
