### ISSUE TITLE
feat: Integrate Negentropy RBSR library for Waku Sync

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#2426]
This issue relates to the implementation of a proposed underlying protocol for Waku Sync as set out in https://github.com/waku-org/research/issues/80
One viable technical solution to achieve is to use a RBSR mechanism similar to that implemented in https://github.com/hoytech/negentropy
This issue tracks the work necessary to integrate this library into nwaku and test its suitability for a sync mechanism.

cc @SionoiS @chaitanyaprem

**Comment by chaitanyaprem** [comment]
After doing some digging wrt issue faced in integrating negentropy and consulting nim team, it has been identified that in order to use the negentropy C++ API directly in nim, it would require nim to be compiled as c++ code instead of C(that is being done currently). This is not recommended by nim team as there are limitations and we may run into issues.

_Note: If there were no templates used in the C++ code, then we could integrate directly into nim by using extern-C, but since negentropy using templates this would not work. [Ref](https://stackoverflow.com/questions/4877705/why-cant-templates-be-within-extern-c-blocks) _ 

Ref Query and pointers:
-  https://discord.com/channels/613988663034118151/616299964242460682/1207675010387419136
- https://status-im.github.io/nim-style-guide/libraries.wrappers.html?highlight=c%2B%2B#cons

Hence as suggested, i am proceeding with writing a C API wrapper for negentropy which can then be used in the Waku-sync code.

**Comment by Ivansete-status** [comment]
In order to validate this properly we can use the `message_counter` utility.
We will also need to validate that the `nwaku` memory doesn't grow too much due to the underlying negentropy library

**Comment by Ivansete-status** [comment]
The only left task:
<<We will also need to validate that the nwaku memory doesn't grow too much due to the underlying negentropy library>>

**Comment by jm-clius** [comment]
Closing issue as done. Any new features/reported issues can be raised separately.
