### ISSUE TITLE
feat: add WakuMessage's `meta` field to db schema

### ISSUE THREAD

**Issue by gabrielmer** [waku-org/nwaku#2432]
### Problem
As a continuation of #2214, we need to add support for storing WakuMessage's `meta` field in our db. For that, we need to update our schema and the db inserts to contain the new field.

### Acceptance criteria
`meta` field gets stored in the db

**Comment by chaitanyaprem** [comment]
@SionoiS I am wondering if this would also be required for Store-v3. 
Because when a store query returns a message, the client can generate the hash again to verify message content is correct. Without meta field proper hash cannot be generated.
Similarly, during sync a Store node fetching message from another Store node can validate message content by computing the hash of received message.

**Comment by SionoiS** [comment]
Yes! We have to store the meta field if present.

https://rfc.vac.dev/spec/14/#deterministic-message-hashing

**Comment by richard-ramos** [comment]
We do not store that field.
I asked @fryorcraken about running store nodes on desktop, and the plan is for this to be done with the nwaku integration.

**Comment by chaitanyaprem** [comment]
> We do not store that field. I asked @fryorcraken about running store nodes on desktop, and the plan is for this to be done with the nwaku integration.

Got it. Thanks.

**Comment by fryorcraken** [comment]
Yes. For now running store in Desktop is out of the picture.
