### ISSUE TITLE
bug: nwaku <> js-waku interop tests failing

### ISSUE THREAD

**Issue by gabrielmer** [waku-org/nwaku#2621]
### Problem
nwaku <> js-waku interop tests have been failing for quite some time.
This issue tracks our stabilization efforts.

**Comment by EmilIvanichkovv** [comment]
I've been investigating the same issue for 2/3 weeks now. @weboko is familiar with some of the details, as we had discussions on Discord. 

I can provide you with the version details of the projects I used, which worked fine.
- For the `js` client I had installed the following versions
  ```json
      "@waku/core": "0.0.17",
      "@waku/interfaces": "0.0.17",
      "@waku/noise": "0.0.3-dc9b797 ",
      "@waku/proto": "0.0.4",
      "@waku/sdk": "0.0.18",
      "@waku/utils": "0.0.10",
   ```
- For the nim client I had the project checked out on [9ef2eccb8aa19e80a9381dcb2ece29718ebce30f](https://github.com/waku-org/nwaku/commit/9ef2eccb8aa19e80a9381dcb2ece29718ebce30f)
 
In the project we are developing, we utilize noise sessions (provided by `js-noise` on the JS side). As you know, the first step is to initiate a handshake. With the versions above, I was able to process it successfully and then exchange encrypted messages between `nwaku` <> `js-waku`.

At some point, the `js-waku` node stopped connecting to peers (more details can be found in Discord), so I was forced to update versions, which of course triggered other discrepancies. With the help of @weboko, most of them were fixed. Now, on the JS side, everything seems to work fine. I am able to start the node and connect to peers.

The main problem now is that the messages I send from `nwaku` to the corresponding pubsub and content topics are never received by the JS instance. Whether I send direct messages or use the handshake utils provided by `nwaku`, the messages do not reach the `js-waku` node. This used to work fine before, but now it's a blocker for us because we rely on Waku for message transfer between the backend and frontend of our app.

If you think more details might be helpful, feel free to reach out to me for a chat.

**Comment by gabrielmer** [comment]
@EmilIvanichkovv thanks so much for the comment.
From what I've seen until now, the interop test failures do not seem to be related to what you're experiencing.

However, will DM you in order to understand and help debug from nwaku side :)

**Comment by gabrielmer** [comment]
Blocked by https://github.com/waku-org/js-waku/issues/2010

**Comment by gabrielmer** [comment]
Closing as it was initially solved. Compatibility breaks with time and should be addressed periodically
