### ISSUE TITLE
bug: timestamp should be set to 0 if not provided in REST API

### ISSUE THREAD

**Issue by kaichaosun** [waku-org/nwaku#2625]
### Problem
I sent messages through `/relay/v1/auto/messages`, and didn't set timestamp, but a auto generated timestamp is stored in database messages table. It's probably better to set it to 0 based on [spec](https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/14/message.md#message-attributes).

### Impact

The timestamp affect the hash of wakumessage, for scenarios like re-send old messages, a auto-generated timestamp may affect the application level solution which depends on the store v3 hash-based query.

### Expected behavior

set timestamp to 0 if not provided.

**Comment by chaitanyaprem** [comment]
IIRC, the idea was to make timestamp a mandatory field in The Waku Network because of RLN. Which is why if a timestamp is not passed by the caller, the API would generate and include the timestamp in the message. This would also make Store queries more deterministic as all messages are stored based on originating timestamp. 


> The timestamp affect the hash of wakumessage, for scenarios like re-send old messages, a auto-generated timestamp may affect the application level solution which depends on the store v3 hash-based query.

Did not understand how the timestamp being filled automatically will affect application. Because the messageHash is generated at Waku REST API layer and returned to the application. If application has to resend a message, it will again pass timestamp as 0 and will get a new hash. So, it can always only store the latest hash of the message which it can then use for store query. 
Maybe you can elaborate more on the scenario you are talking about so that i can understand.

**Comment by chaitanyaprem** [comment]
> If a new hash is used, app can't use the old one to query the message.

If you see status-go (https://github.com/status-im/status-go/blob/11dc6976bdadd9c80ddcbc6897e647c5246b7ab7/wakuv2/waku.go#L1041) , every time a message is retransmitted, the timestamp of message is changed which results in a new hash. 

Also note, status-go uses something called as envelopeID to uniquely identify application payload, different that WakuMessagehash.  

Thanks for sharing the above interesting discussion. After going through, i have few comments or questions.

1. If WakuMessage.timestamp is not to be used by applications at all and is meant to indicate `routed-at` for a message, then wouldn't it be better if it is always filled/set by Waku relay rather than getting it from application? This would remove confusion for applications as it will always be filled/set by Waku relay. 

2. I had noticed that for RLN proof generation, msgTimestamp is not used rather currentTime during proofGeneration. Similar approach can be taken for WakuMessage.timestamp where it is always filled in relay.

**Comment by jm-clius** [comment]
Deserves some consideration -
it could be a valid model to have the API _always_ set the timestamp. However, I do think applications sometimes prefer control over this timestamp (as it's the one that is queryable via Store). For example, if this external Waku timestamp matches the internal message timestamp, certain assumptions become easier for querying use cases. The restriction that it should closely match the publish (or routed-at) time is not generally an issue outside of app-level retransmissions or reordering. For interest's sake, does status-go set this Waku timestamp explicitly and is it used for some message ordering/querying on the application level?

**Comment by chaitanyaprem** [comment]
> For interest's sake, does status-go set this Waku timestamp explicitly and is it used for some message ordering/querying on the application level?

Yes, status-go sets this timestamp explicitly. 
IIRC the timestamp is not used for any message ordering within status-go. 


> I do think applications sometimes prefer control over this timestamp (as it's the one that is queryable via Store).

You mean for range based store queries. That is something i have forgotten about.

**Comment by gabrielmer** [comment]
Is there an action item for this issue? Or the behavior is correct and if the application wants to have control over the timestamp then they should set it themselves?

**Comment by gabrielmer** [comment]
> We need to match the implementation (nwaku) with spec, or modify the spec to use latest timestamp if not provided. Also it would be helpful if we make it clear in sepc how we use the timestamp in relay and store. @gabrielmer cc @jm-clius

Talking about this with @jm-clius, he mentioned that this spec is not related to what we do for the users in the REST API, it refers to how we use the timestamp field at the protocol level.

So we don't really have to update the spec if we set it for the REST user if they don't set it themselves. They are two completely different things.

Closing this issue then
