### ISSUE TITLE
bug: RLN_RELAY_MSG_LIMIT handling

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2822]
### Problem
Setting `RLN_RELAY_MSG_LIMIT >= 21` triggers a node restart after a while. 
When running the `waku-simulator` compose with that value, containers restart after some 10s~. Right before that, messages like 
```
nwaku_5                   | ERR 2024-06-18 14:56:29.495+00:00 failure while registering credentials on-chain topics="rln_keystore_generator" tid=380 file=rln_keystore_generator.nim:72 error="index out of bounds, the container is empty"
```
 are printed. And after this the containers restart.

@stubbsta Verified that "the max value for user message limit is set to 20 in the contract and it's not configurable".

### To reproduce
Run a RLN+Relay-enabled nwaku node with the environment variable `RLN_RELAY_MSG_LIMIT` set to  `>= 21`.

### Expected behavior
The node handles that scenario gracefully, exiting early and printing an appropriate error message.

### nwaku version/commit hash
- wakunode2: `version / git commit hash 8e7e72`

**Comment by alrevuelta** [comment]
imho in order to close this and related to https://github.com/waku-org/nwaku/pull/2867 we should just gracefully handle the scenario where someone tries to register with a userMessageLimit greater than allowed. But no need to enforce any limit, since it will be network/cluster specific. In other words, improve error handling, and that's it.
