### ISSUE TITLE
`wakunode2` CLI option to truncate peer storage on startup

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#774]
### Background

Currently once a peer is stored in the persistent DB, it will be reloaded into the peer store after a `wakunode2` restarts.
This may not always be desired behaviour. When a waku-client switches fleets/networks, for example, they may want to clear all existing peers and connections.

### Acceptance criteria

- [ ] CLI config parameter to truncate peer table on startup

### Nice to have

- [ ] Admin API method to truncate peer table and clear peer store on a running node

cc @richard-ramos

**Comment by jm-clius** [comment]
@alrevuelta I think we're going in quite a different direction in terms of peer persistence and managing storage. Happy if we close this stale issue? Feel free to reopen if not. :)

**Comment by alrevuelta** [comment]
@jm-clius Yes, with the new approach peers failing more than x times will be automatically removed, but this can take some time.

Regarding the cli flag, not sure that would be a good idea, since that would involve modifying the deployment files (adding it) and then modifying them (removing it). Not sure if thats practical.

And as a general comment, not sure how relevant the peer persistance feature in general is. Peer discovery is quite fast, and nodes just require few dozens of connected peers to work. So not sure if the benefits of keeping track of old peers outweights the cons: extra complexity, deal with old-no-longer-online peers, etc.

And indirectly we alreadey have peer persistance with dns-disc and service peers (`storenode`, `lightpushnode`, etc).

**Comment by jm-clius** [comment]
Thanks for the feedback!
